AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sasaservice

  Sample SAM Template for sasaservice
  
# Globals
Globals:
  Function:
    Timeout: 29
    MemorySize: 128
    Runtime: nodejs24.x

Parameters:
  DomainName:
    Type: String
    Description: The primary domain for this website.
  AcmCertificateId:
    Type: String
    Description: The ID of the ACM SSL certificate.

Resources:
  SaasApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: 
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        # AllowOrigin: !Sub "'https://${DomainName}'"
        AllowOrigin: "'*'"
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/common-layer
      LayerName: common-layer
      Description: is-letter-s create-response-object
      CompatibleRuntimes:
        - nodejs24.x
    Metadata:
      BuildMethod: nodejs24.x
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/get.handler
      Layers: 
        - !Ref CommonLayer
      Architectures:
        - x86_64
      Events:
        SaasGet:
          Type: Api
          Properties:
            Path: /v1
            Method: get
            RestApiId: !Ref SaasApi
  PostFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers/post.handler
      Layers: 
        - !Ref CommonLayer
      Architectures:
        - x86_64
      Events:
        SaasPost:
          Type: Api
          Properties:
            Path: /v1
            Method: post
            RestApiId: !Ref SaasApi
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig: 
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${AcmCertificateId}"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        Origins:
          # Static S3 assets
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: ApigOrigin
            DomainName: !Sub "${SaasApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
            OriginPath: "/prod"
        # Default routing to S3 static 
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        # Routing for API calls
        CacheBehaviors:
          - PathPattern: /v1/*
            TargetOriginId: ApigOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: 
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            # CachedMethods: 
            #   - HEAD
            #   - GET
            DefaultTTL: 0 # To bypass CDN cache for dynami API calls
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
              Cookies:
                Forward: all
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"

Outputs:
  WebsiteURL:
    Description: Production URL
    Value: !Sub "https://${DomainName}"
  BackendApiURL:
    Description: Unified APIG endpoint via CF
    Value: !Sub "https://${DomainName}/v1"
